# Assert
다음과 같은 예시를 보겠습니다.

```
assert 2 > 1
print("YES. 2 is bigger than 1")
```

위의 에시는 만일 2가 1보다 크면 에러 없이 넘어 갑니다. 하지만 만일 assert 다음에 나오는 분리언이 거짓이라면 에러가 생깁니다.

다음의 예시는 우리만의 에러를 만드는 방법입니다.

```
assert 1 > 2, "흠... 에러와 🐛🐛🐛"
```
